/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : EInt1.H
**     Project   : monofan
**     Processor : MC9S08SH8CPJ
**     Component : ExtInt
**     Version   : Component 02.094, Driver 01.19, CPU db: 3.00.062
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 18/01/2016, 11:54 a.m.
**     Abstract  :
**         This bean "ExtInt" implements an external 
**         interrupt, its control methods and interrupt/event 
**         handling procedure.
**         The bean uses one pin which generates interrupt on 
**         selected edge.
**     Settings  :
**         Interrupt name              : Virq
**         User handling procedure     : EInt1_OnInterrupt
**
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       1             |  PTA5_IRQ_TCLK_RESET
**             ----------------------------------------------------
**
**         Port name                   : PTA
**
**         Bit number (in port)        : 5
**         Bit mask of the port        : $0020
**
**         Signal edge/level           : low
**         Priority                    : 
**         Pull option                 : off
**         Initial state               : Enabled
**
**         Edge register               : IRQSC     [$001A]
**         Enable register             : IRQSC     [$001A]
**         Request register            : IRQSC     [$001A]
**
**         Port data register          : PTAD      [$0000]
**         Port control register       : PTADD     [$0001]
**     Contents  :
**         GetVal - bool EInt1_GetVal(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __EInt1_H
#define __EInt1_H

/* MODULE EInt1. */



/*Including shared modules, which are used in the whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"


__interrupt void EInt1_Interrupt(void);
/*
** ===================================================================
**     Method      :  EInt1_Interrupt (component ExtInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#define EInt1_GetVal() \
  ((bool)((PTAD) & 0x20))

/*
** ===================================================================
**     Method      :  EInt1_GetVal (component ExtInt)
**
**     Description :
**         Returns the actual value of the input pin of the bean.
**     Parameters  : None
**     Returns     :
**         ---             - Returned input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
** ===================================================================
*/
#endif /* __EInt1_H*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
