/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : FLASH1.H
**     Project   : monofan
**     Processor : MC9S08SH8CPJ
**     Component : Init_FLASH
**     Version   : Component 01.044, Driver 01.13, CPU db: 3.00.062
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 01/02/2016, 08:41 a.m.
**     Abstract  :
**          This file implements the FLASH (IntFLASH) module initialization 
**          according to the Peripheral Initialization Bean settings, and defines
**          interrupt service routines prototypes. 
**     Settings  :
**          Bean name                                      : FLASH1
**          Device                                         : IntFLASH
**          Clock settings                                 : 
**            Divide flash clock by 8                      : no
**            Clock Divider                                : 20
**            Frequency (150kHz - 200kHz)                  : 200 kHz
**          Initialization                                 : 
**            Call Init method                             : yes
**     Contents  :
**         Init - void FLASH1_Init(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __FLASH1
#define __FLASH1

/* MODULE FLASH1. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "Cpu.h"




void FLASH1_Init(void);
/*
** ===================================================================
**     Method      :  FLASH1_Init (component Init_FLASH)
**
**     Description :
**         This method initializes registers of the FLASH module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END FLASH1. */

#endif /* ifndef __FLASH1 */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
